### ISSUE TITLE
Error is coming when tring to generate reports with maven : Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException 

### ISSUE THREAD

**Issue by abhi8130** [allure-framework/allure-maven#129]
Need support to generate the allure reports by using maven, but unfortunately it couldn't possible.
**Error:**
[INFO] --- allure-maven:2.8:report (default-cli) @ YovoAutomation ---
[INFO] Allure installation directory E:\Appium\YovoAutomation/.allure
[INFO] Try to finding out allure 2.3.1
[INFO] Generate Allure report (report) with version 2.3.1
[INFO] Generate Allure report to E:\Appium\YovoAutomation\target\site/allure-mav
en-plugin
[INFO] Found results directory E:\Appium\YovoAutomation\target\allure-results
[INFO] Can't find information about categories.
[INFO] Generate report to E:\Appium\YovoAutomation\target\site\allure-maven-plug
in
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBEx
ception
        at io.qameta.allure.allure1.Allure1Plugin.xmlFiles(Allure1Plugin.java:37
5)
        at io.qameta.allure.allure1.Allure1Plugin.getStreamOfAllure1Results(Allu
re1Plugin.java:370)
        at io.qameta.allure.allure1.Allure1Plugin.readResults(Allure1Plugin.java
:101)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator
.java:32)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:32)

        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipe
line.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipe
line.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(A
rrayList.java:1621)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline
.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractP
ipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Redu
ceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline
.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipelin
e.java:578)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:54)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
        at io.qameta.allure.Commands.generate(Commands.java:88)
        at io.qameta.allure.CommandLine.run(CommandLine.java:129)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at io.qameta.allure.CommandLine.main(CommandLine.java:72)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinCla
ssLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(C
lassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 20 more
[ERROR] Can't generate allure report data
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit
value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.
java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166
)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:153
)
    at io.qameta.allure.maven.AllureCommandline.execute (AllureCommandline.java:
79)
    at io.qameta.allure.maven.AllureCommandline.generateReport (AllureCommandlin
e.java:49)
    at io.qameta.allure.maven.AllureGenerateMojo.generateReport (AllureGenerateM
ojo.java:189)
    at io.qameta.allure.maven.AllureGenerateMojo.executeReport (AllureGenerateMo
jo.java:128)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenRep
ort.java:255)
    at org.apache.maven.reporting.AbstractMavenReport.execute (AbstractMavenRepo
rt.java:143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBui
ldPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
va:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
va:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
va:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreaded
Builder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleSt
arter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccesso
rImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMetho
dAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launche
r.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:2
25)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launc
her.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347
)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.741 s
[INFO] Finished at: 2020-05-30T09:24:55+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.qameta.allure:allure-maven:2.8:report (default
-cli) on project YovoAutomation: An error has occurred in Allure report generati
on.: Could not generate the report: Can't generate allure report data: Process e
xited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

**Pom.xml**
			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>2.8</version>
				<configuration>
					<reportVersion>2.3.1</reportVersion>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-testng</artifactId>
			<version>2.13.1</version>
		</dependency>

**Comment by 22f** [comment]
@abhi8130 try new `2.10.0` version of allure-maven.
