### ISSUE TITLE
Allure plugin should use the same java version as maven's root process

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-maven#47]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Java 8 and 9 are installed. Maven is set up to use Java 8 in IDE.
While report generation via `allure:report`, `allure-maven` plugin uses Java specified via `JAVA_HOME` (9th version), which causes Java 9 specific exception.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Install Java 8 and Java 9.
2. Set JAVA_HOME pointing to JDK 9 folder.
3. Force Maven using JDK 8 in IntelliJ configuration.
4. Run any test using `allure-testng` adaptor.
5. Generate report via `allure:report` from IDE.

#### What is the expected behavior?
`allure-maven` plugin uses the same Java version as the root maven process.

#### What is the motivation / use case for changing the behavior?
Currently it's not possible to generate report without overriding `JAVA_HOME`, as in Java 9 there were some structural changes made, which cause `javax` exceptions.

#### Please tell us about your environment:

- Allure version:        2.3.4
- Test framework:        testng@6.11
- Allure adaptor:        allure-testng@2.0-BETA16
- Generate report using: allure-maven@2.8

#### Other information 
Stacktrace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at io.qameta.allure.allure1.Allure1Plugin.xmlFiles(Allure1Plugin.java:375)
	at io.qameta.allure.allure1.Allure1Plugin.getStreamOfAllure1Results(Allure1Plugin.java:370)
	at io.qameta.allure.allure1.Allure1Plugin.readResults(Allure1Plugin.java:101)
	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:32)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:54)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
	at io.qameta.allure.Commands.generate(Commands.java:88)
	at io.qameta.allure.CommandLine.run(CommandLine.java:129)
	at java.base/java.util.Optional.orElseGet(Optional.java:361)
	at io.qameta.allure.CommandLine.main(CommandLine.java:72)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 20 more
```

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
can't reproduce the problem. Allure Maven plugin uses the same version of java that maven did

**Comment by baev** [comment]
Maybe the problem is that you are uses bundled Maven from IDE?

**Comment by andrey-ryoo** [comment]
Have the same issue
Oracle JDK 9.0.4
Maven 3.5.3
Allure 2.6.0
TestNG 6.14.2
AspectJ 1.9.0.RC2
InteliJ IDEA 2017.3.4

`java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.access$100(ServiceLoader.java:390)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:799)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1389)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:967)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:906)
	at org.testng.TestNG.initializeEverything(TestNG.java:996)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:139)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:126)
	at io.qameta.allure.model.Allure2ModelJackson.createMapper(Allure2ModelJackson.java:26)
	at io.qameta.allure.FileSystemResultsWriter.<init>(FileSystemResultsWriter.java:30)
	at io.qameta.allure.AllureLifecycle.getDefaultWriter(AllureLifecycle.java:281)
	at io.qameta.allure.AllureLifecycle.<init>(AllureLifecycle.java:47)
	at io.qameta.allure.Allure.getLifecycle(Allure.java:30)
	at io.qameta.allure.testng.AllureTestNg.<init>(AllureTestNg.java:119)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:777)
	... 8 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 21 more`

**Comment by andrey-ryoo** [comment]
But works with mvn test ...

**Comment by etki** [comment]
It seems that previously available core classes have been moved to module and then deprecated in java 12. Is it possible to try to add following dependency to plugin?

```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.2.11</version>
</dependency>
```

I believe that will resolve the issue with missing deps on j9+

**Comment by writetomaha** [comment]
can i generate the allure reports without Java Installation, I am using allure bdd for python. without Java i am unable to generate the reports

**Comment by uterator** [comment]
with `<reportVersion>2.7.0</reportVersion>` it was able to generate the report
