### ISSUE TITLE
Error while aggregating report on Windows

### ISSUE THREAD

**Issue by aiannucci** [allure-framework/allure-maven#49]
#### I'm submitting a ... 
  - [X] bug report

#### What is the current behavior?

Maven multi-module project results aggregation fails in Windows

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

I got into this problem while running `mvn io.qameta.allure:allure-maven:2.8:aggregate -Dreport.version=2.3.4` on a multi-module Maven project.
Error apparently comes from Allure command line, but not sure.

#### Environment

- OS: Windows 2016
- Allure version:        2.3.4
- Test framework:        junit@4.12
- Allure adaptor:        allure-junit4@2.0-BETA17
- Generate report using: allure-maven@2.8

#### Stacktrace

```
[ERROR] Failed to execute goal io.qameta.allure:allure-maven:2.8:aggregate (default-cli) on project mule-runtime-project: An error has occurred in Allure report generation. Could not generate the report: Can't generate allure report data: Process exited with an error: 255 (Exit value: 255) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.qameta.allure:allure-maven:2.8:aggregate (default-cli) on project mule-runtime-project: An error has occurred in Allure report generation.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in Allure report generation.
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:171)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.reporting.MavenReportException: Could not generate the report
        at io.qameta.allure.maven.AllureGenerateMojo.executeReport(AllureGenerateMojo.java:132)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
        ... 22 more
Caused by: org.apache.maven.reporting.MavenReportException: Can't generate allure report data
        at io.qameta.allure.maven.AllureGenerateMojo.generateReport(AllureGenerateMojo.java:193)
        at io.qameta.allure.maven.AllureGenerateMojo.executeReport(AllureGenerateMojo.java:128)
        ... 24 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 255 (Exit value: 255)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at io.qameta.allure.maven.AllureCommandline.execute(AllureCommandline.java:79)
        at io.qameta.allure.maven.AllureCommandline.generateReport(AllureCommandline.java:49)
        at io.qameta.allure.maven.AllureGenerateMojo.generateReport(AllureGenerateMojo.java:189)
        ... 25 more
```

**Comment by aiannucci** [comment]
The above works fine in macOS and Linux
